export * from './Animals/Animals'
export * from './Brainwave/Brainwave'
export * from './Knowledge/Knowledge'
export * from './Logout/Logout'
export * from './Computer/Computer'
export * from './Geography/Geography'
