export * from './Dashboard/Dashboard'
export * from './Description/Description'
export * from './SignIn/SignIn'
export * from './SignUp/SignUp'
export * from './Result/Result'
export * from './Quiz/Quiz'
